name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache mvn modules
        id: cache-mvn
        uses: actions/cache@v3
        env:
          cache-name: cache-mvn-packages
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-dkb-url-shortner
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache mvn modules
        id: cache-mvn
        uses: actions/cache@v3
        env:
          cache-name: cache-mvn-packages
        with:
          path: ~/.m2
          key: ${{ runner.os }}-test-${{ env.cache-name }}-dkb-url-shortner
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Maven
        run: ./mvnw -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
